name: CI-CD TodoList

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore ./TodoList/TodoList.csproj

      - name: Build
        run: dotnet build ./TodoList/TodoList.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal || echo "No tests, skipping"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./TodoList
          file: ./TodoList/Dockerfile
          push: true
          tags: kirnik55/todolist:latest

  deploy:
    runs-on: self-hosted
    needs: build-test-and-push

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to Kubernetes (minikube)
        env:
          KUBECONFIG: 'C:\Users\Mario\.kube\config'  
        run: |
          kubectl config current-context
          kubectl apply -f k8s/mongo.yaml
          kubectl apply -f k8s/todo-api.yaml
          kubectl get pods -A
